# Generated by Django 5.2.5 on 2025-09-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_invite_company_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='department',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('design', 'Design'), ('product', 'Product'), ('other', 'Other')], default='hr', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('design', 'Design'), ('product', 'Product'), ('other', 'Other')], default='hr', max_length=32),
        ),
    ]
