# Generated by Django 5.2.5 on 2025-10-01 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_invite_department_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.company'),
            preserve_default=False,
        ),
    ]
