# Generated by Django 5.2.10 on 2026-01-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_question_assignment_response_survey_question_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
    ]
