# Generated by Django 5.2.10 on 2026-02-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_survey_emails_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('account', 'Account'), ('assessment', 'Assessment'), ('survey', 'Survey')], max_length=20)),
                ('audience_type', models.CharField(choices=[('employee', 'Employee'), ('candidate', 'Candidate')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('variables', models.JSONField(default=dict, help_text='Allowed placeholders like {{firstName}}, {{surveyLink}}')),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, help_text='Optional: Template specific to a company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='accounts.company')),
            ],
        ),
    ]
