# Generated by Django 5.2.5 on 2025-08-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
