# Generated by Django 5.2.5 on 2025-08-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assignment_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='score',
            new_name='metrics',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='assignment',
            name='ai_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttemplate'),
        ),
    ]
