# Generated by Django 5.2.5 on 2025-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_rename_score_assignment_metrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
