# Generated by Django 5.2.10 on 2026-01-18 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_department_icon'),
        ('assessments', '0004_assignment_assigned_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('ai_report', models.TextField(blank=True, null=True)),
                ('recruitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.recruitee')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmenttemplate')),
            ],
            options={
                'unique_together': {('recruitee', 'template')},
            },
        ),
    ]
