# Generated by Django x.x.x on YYYY-MM-DD HH:MM

from django.db import migrations

def populate_templates(apps, schema_editor):
    AssessmentTemplate = apps.get_model('assessments', 'AssessmentTemplate')
    templates = [
        ("BIG_FIVE", "Big Five Personality Test"),
        ("KARASEK", "Karasek Job Strain Model"),
        ("MASLACH", "Maslach Burnout Inventory"),
        ("DISC", "DISC Personality Test"),
        ("JSS", "Job Satisfaction Survey"),
        ("BRS", "Brief Resilience Scale"),
        ("CDRISC10", "Connor-Davidson Resilience Scale"),
        ("WSES", "Work Self-Efficacy Scale"),
        ("GCOS", "General Causality Orientation Scale"),
        ("RIBS", "Runco Ideational Behavior Scale"),
        ("CAQ", "Creative Achievement Questionnaire"),
        ("ISE", "Innovation Self-Efficacy"),
    ]
    for code, name in templates:
        AssessmentTemplate.objects.get_or_create(code=code, defaults={'name': name})

class Migration(migrations.Migration):

    # <--- HERE: put the last real migration file of assessments
    dependencies = [
        ('assessments', '0005_candidateassignment'),  
    ]

    operations = [
        migrations.RunPython(populate_templates),
    ]
