# Generated by Django 5.2.11 on 2026-03-25 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_employment_status'),
        ('assessments', '0006_populate_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(help_text="e.g. 'engineering', 'all'", max_length=64)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status_filter', models.CharField(default='all', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overview_data', models.JSONField(blank=True, default=dict)),
                ('aggregated_metrics', models.JSONField(blank=True, default=dict)),
                ('trends', models.JSONField(blank=True, default=dict)),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.JSONField(blank=True, default=dict)),
                ('employee_breakdown', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_reports', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
