# Generated by Django 5.2.11 on 2026-03-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_departmentreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentReport',
        ),
    ]
