# Generated by Django 5.2.11 on 2026-03-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_delete_departmentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
