export const COLORS = {
  primary: "var(--primary)",
  primaryLight: "var(--primary-light)",
  primaryDark: "var(--primary-dark)",
  secondary: "var(--secondary)",
  blue: "var(--blue)",
  blueLight: "var(--blue-light)",
  purple: "var(--purple)",
  purpleLight: "var(--purple-light)",
  orange: "var(--orange)",
  orangeLight: "var(--orange-light)",
  red: "var(--red)",
  dark: "var(--dark)",
  bgMain: "var(--bg-main)",
  cardBg: "var(--card-bg)",
  textPrimary: "var(--text-primary)",
  textSecondary: "var(--text-secondary)",
  textMuted: "var(--text-muted)",
  borderColor: "var(--border-color)",
  shadowSm: "var(--shadow-sm)",
  shadowMd: "var(--shadow-md)",
  shadowLg: "var(--shadow-lg)",
  shadowHuge: "var(--shadow-huge)",
  tableRow: "var(--table-row)",
};

export const ASSESSMENT_OPTIONS = [
  {
    group: "Personality & Behavior",
    items: [
      { code: "BIG_FIVE", label: "🧠 Big Five Personality Traits" },
      { code: "DISC", label: "💼 DISC Personality Assessment" },
    ],
  },
  {
    group: "Resilience & Self-Efficacy",
    items: [
      { code: "BRS", label: "💪 Brief Resilience Scale" },
      { code: "CDRISC10", label: "🛡️ Connor-Davidson Resilience" },
      { code: "WSES", label: "✨ Work Self-Efficacy Scale" },
    ],
  },
  {
    group: "Work Style & Motivation",
    items: [
      { code: "KARASEK", label: "⚖️ Karasek Job Demand-Control" },
      { code: "GCOS", label: "🎯 General Causality Orientations" },
    ],
  },
  {
    group: "Cognitive & Creativity",
    items: [
      { code: "RIBS", label: "💡 Runco Ideational Behavior" },
      { code: "CAQ", label: "🎨 Creative Achievement" },
      { code: "ISE", label: "🚀 Innovation Self-Efficacy" },
    ],
  },
];

export const styles = {
  container: {
    padding: "5px 14px",
    backgroundColor: COLORS.bgMain,
    minHeight: "100vh",
    fontFamily: "'Inter', system-ui, sans-serif",
    color: COLORS.textPrimary,
  },
  mainWrapperCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: "24px",
    border: `1px solid ${COLORS.borderColor}`,
    boxShadow: COLORS.shadowHuge,
    margin: "0 auto",
    padding: "48px",
    minHeight: "calc(100vh - 40px)",
    display: "flex",
    flexDirection: "column",
  },
  card: {
    backgroundColor: COLORS.cardBg,
    borderRadius: "16px",
    border: `1px solid ${COLORS.borderColor}`,
    boxShadow: COLORS.shadowSm,
    overflow: "hidden",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
  },
  btnPrimary: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 20px",
    backgroundColor: COLORS.primary,
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  btnBulk: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 20px",
    backgroundColor: COLORS.blue,
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  input: {
    padding: "12px 16px",
    borderRadius: "10px",
    border: `1px solid ${COLORS.borderColor}`,
    fontSize: "14px",
    width: "100%",
    outline: "none",
    transition: "border-color 0.2s",
    backgroundColor: "#fff",
  },
  label: {
    display: "block",
    marginBottom: "6px",
    fontSize: "14px",
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  badge: (status) => {
    const badgeColors = {
      hired: { bg: "#ecfdf5", text: "#059669" },
      rejected: { bg: "#fef2f2", text: "#ef4444" },
      invited: { bg: "#eff6ff", text: "#3b82f6" },
      pending: { bg: "#fffbeb", text: "#d97706" },
      interview: { bg: "#fef3c7", text: "#d97706" },
      completed: { bg: "#ecfdf5", text: "#059669" },
      default: { bg: "#f3f4f6", text: "#6b7280" },
    };
    const style = badgeColors[status?.toLowerCase()] || badgeColors.default;
    return {
      padding: "4px 12px",
      borderRadius: "99px",
      fontSize: "12px",
      fontWeight: "600",
      backgroundColor: style.bg,
      color: style.text,
      textTransform: "capitalize",
    };
  },
  checkbox: {
    width: "18px",
    height: "18px",
    cursor: "pointer",
    accentColor: COLORS.primary,
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 23, 42, 0.4)",
    backdropFilter: "blur(6px)",
    display: "grid",
    placeItems: "center",
    zIndex: 9999,
    padding: 20,
  },
};
